from typing import Dict, List

landtable: Dict[str, int] = {
    "Icy Land":                 0x00,
    "Living Cave":              0x01,
    "Desert":                   0x02,
    "Jungle":                   0x03,
    "Alchemist Lab":            0x04,
    "Hall of Mirrors":          0x05,
    "Graveyard":                0x06,
    "Hell":                     0x07,
    "R'Lyeh":                   0x08,
    "Land of Eternal Motion":   0x09,
    "Cocytus":                  0x0A,
    "Dry Forest":               0x0B,
    "Vineyard":                 0x0C,
    "Dead Cave":                0x0D,
    "Hive":                     0x0E,
    "Emerald Mine":             0x0F,
    "Land of Power":            0x10,
    # Camelot is a special land, hence at the bottom
    "Temple of Cthulhu":        0x12,
    "Carribean":                0x13,
    "Red Rock Valley":          0x14,
    "Minefield":                0x15,
    "Ocean":                    0x16,
    "Whirlpool":                0x17,
    "Palace":                   0x18,
    "Living Fjord":             0x19,
    "Ivory Tower":              0x1A,
    "Zebra":                    0x1B,
    "Elemental Planes":         0x1C,
    "Land of Storms":           0x1D,
    "Overgrown Woods":          0x1E,
    "Clearing":                 0x1F,
    "Haunted Woods":            0x20,
    "Windy Plains":             0x21,
    "Rose Garden":              0x22,
    "Warped Coast":             0x23,
    "Galapagos":                0x24,
    "Yendorian Forest":         0x25,
    "Dragon Chasms":            0x26,
    "Kraken Depths":            0x27,
    "Burial Grounds":           0x28,
    "Trollheim":                0x29,
    "Dungeon":                  0x2A,
    "Lost Mountain":            0x2B,
    "Reptiles":                 0x2C,
    "Prairie":                  0x2D,
    "Bull Dash":                0x2E,
    "Volcanic Wasteland":       0x2F,
    "Hunting Ground":           0x30,
    "Blizzard":                 0x31,
    "Terracotta Army":          0x32,
    "Ruined City":              0x33,
    "Jelly Kingdom":            0x34,
    "Brown Island":             0x35,
    "Free Fall":                0x36,
    "Irradiated Field":         0x37,
    "Wetland":                  0x38,
    "Frog Park":                0x39,
    "Eclectic City":            0x3A,
    "Cursed Canyon":            0x3B,
    "Dice Reserve":             0x3C,
    # Special lands
    "Camelot":                  0x11,
}

landlist: List[str] = landtable.keys()