from typing import Dict, NamedTuple, Optional

from BaseClasses import Location
from .Names import LocationName


hyperrogue_base_id: int = 0xCBA000

class HyperrogueLocation(Location):
    game = "Hyperrogue"


class HyperrogueLocationData(NamedTuple):
    region: str
    address: Optional[int] = None

unlock_location_data_table: Dict[str, HyperrogueLocationData] = {
    LocationName.ice_diamond_1:         HyperrogueLocationData("Icy Land",                  hyperrogue_base_id + 0x000),
    LocationName.gold_1:                HyperrogueLocationData("Living Caves",              hyperrogue_base_id + 0x001),
    LocationName.spice_1:               HyperrogueLocationData("Desert",                    hyperrogue_base_id + 0x002),
    LocationName.ruby_1:                HyperrogueLocationData("Jungle",                    hyperrogue_base_id + 0x003),
    LocationName.elixir_of_life_1:      HyperrogueLocationData("Alchemist Lab",             hyperrogue_base_id + 0x004),
    LocationName.shard_1:               HyperrogueLocationData("Hall of Mirrors",           hyperrogue_base_id + 0x005),
    LocationName.necromancers_totem_1:  HyperrogueLocationData("Graveyard",                 hyperrogue_base_id + 0x006),
    LocationName.demon_daisy_1:         HyperrogueLocationData("Hell",                      hyperrogue_base_id + 0x007),
    LocationName.statue_of_cthulhu_1:   HyperrogueLocationData("R'Lyeh",                    hyperrogue_base_id + 0x008),
    LocationName.phoenix_feather_1:     HyperrogueLocationData("Land of Eternal Motion",    hyperrogue_base_id + 0x009),
    LocationName.ice_sapphire_1:        HyperrogueLocationData("Cocytus",                   hyperrogue_base_id + 0x00A),
    LocationName.fern_flower_1:         HyperrogueLocationData("Dry Forest",                hyperrogue_base_id + 0x00B),
    LocationName.wine_1:                HyperrogueLocationData("Vineyard",                  hyperrogue_base_id + 0x00C),
    LocationName.silver_1:              HyperrogueLocationData("Dead Caves",                hyperrogue_base_id + 0x00D),
    LocationName.royal_jelly_1:         HyperrogueLocationData("Hive",                      hyperrogue_base_id + 0x00E),
    LocationName.emerald_1:             HyperrogueLocationData("Emerald Mines",             hyperrogue_base_id + 0x00F),
    LocationName.powerstone_1:          HyperrogueLocationData("Land of Power",             hyperrogue_base_id + 0x010),
    LocationName.holy_grail_1:          HyperrogueLocationData("Camelot",                   hyperrogue_base_id + 0x011),
    LocationName.grimoire_1:            HyperrogueLocationData("Temple of Cthulhu",         hyperrogue_base_id + 0x012),
    LocationName.pirate_treasure_1:     HyperrogueLocationData("Carribean",                 hyperrogue_base_id + 0x013),
    LocationName.red_gem_1:             HyperrogueLocationData("Red Rock Valley",           hyperrogue_base_id + 0x014),
    LocationName.bomberbird_egg_1:      HyperrogueLocationData("Minefield",                 hyperrogue_base_id + 0x015),
    LocationName.amber_1:               HyperrogueLocationData("Ocean",                     hyperrogue_base_id + 0x016),
    LocationName.pearl_1:               HyperrogueLocationData("Whirlpool",                 hyperrogue_base_id + 0x017),
    LocationName.hypersian_rug_1:       HyperrogueLocationData("Palace",                    hyperrogue_base_id + 0x018),
    LocationName.garnet_1:              HyperrogueLocationData("Living Fjord",              hyperrogue_base_id + 0x019),
    LocationName.ivory_figurine_1:      HyperrogueLocationData("Ivory Tower",               hyperrogue_base_id + 0x01A),
    LocationName.onyx_1:                HyperrogueLocationData("Zebra",                     hyperrogue_base_id + 0x01B),
    LocationName.elemental_gem_1:       HyperrogueLocationData("Elemental Planes",          hyperrogue_base_id + 0x01C),
    LocationName.fulgurite_1:           HyperrogueLocationData("Land of Storms",            hyperrogue_base_id + 0x01D),
    LocationName.mutant_sapling_1:      HyperrogueLocationData("Overgrown Woods",           hyperrogue_base_id + 0x01E),
    LocationName.mutant_fruit_1:        HyperrogueLocationData("Clearing",                  hyperrogue_base_id + 0x01F),
    LocationName.black_lotus_1:         HyperrogueLocationData("Haunted Woods",             hyperrogue_base_id + 0x020),
    LocationName.white_dove_feather_1:  HyperrogueLocationData("Windy Plains",              hyperrogue_base_id + 0x021),
    LocationName.thornless_rose_1:      HyperrogueLocationData("Rose Garden",               hyperrogue_base_id + 0x022),
    LocationName.coral_1:               HyperrogueLocationData("Warped Coast",              hyperrogue_base_id + 0x023),
    LocationName.baby_tortoise_1:       HyperrogueLocationData("Galapagos",                 hyperrogue_base_id + 0x024),
    LocationName.apple_1:               HyperrogueLocationData("Yendorian Forest",          hyperrogue_base_id + 0x025),
    LocationName.dragon_scale_1:        HyperrogueLocationData("Dragon Chasms",             hyperrogue_base_id + 0x026),
    LocationName.sunken_treasure_1:     HyperrogueLocationData("Kraken Depths",             hyperrogue_base_id + 0x027),
    LocationName.ancient_jewelry_1:     HyperrogueLocationData("Burial Grounds",            hyperrogue_base_id + 0x028),
    LocationName.golden_egg_1:          HyperrogueLocationData("Trollheim",                 hyperrogue_base_id + 0x029),
    LocationName.slime_mold_1:          HyperrogueLocationData("Dungeon",                   hyperrogue_base_id + 0x02A),
    LocationName.amethyst_1:            HyperrogueLocationData("Lost Mountain",             hyperrogue_base_id + 0x02B),
    LocationName.dodecahedron_1:        HyperrogueLocationData("Reptiles",                  hyperrogue_base_id + 0x02C),
    LocationName.green_grass_1:         HyperrogueLocationData("Prairie",                   hyperrogue_base_id + 0x02D),
    LocationName.spinel_1:              HyperrogueLocationData("Bull Dash",                 hyperrogue_base_id + 0x02E),
    LocationName.lava_lily_1:           HyperrogueLocationData("Volcanic Wasteland",        hyperrogue_base_id + 0x02F),
    LocationName.turquoise_1:           HyperrogueLocationData("Hunting Ground",            hyperrogue_base_id + 0x030),
    LocationName.forgotten_relic_1:     HyperrogueLocationData("Blizzard",                  hyperrogue_base_id + 0x031),
    LocationName.ancient_weapon_1:      HyperrogueLocationData("Terracotta Army",           hyperrogue_base_id + 0x032),
    LocationName.chrysoberyl_1:         HyperrogueLocationData("Ruined City",               hyperrogue_base_id + 0x033),
    LocationName.tasty_jelly_1:         HyperrogueLocationData("Jelly Kingdom",             hyperrogue_base_id + 0x034),
    LocationName.tigers_eye_1:          HyperrogueLocationData("Brown Island",              hyperrogue_base_id + 0x035),
    LocationName.meteorite_1:           HyperrogueLocationData("Free Fall",                 hyperrogue_base_id + 0x036),
    LocationName.torbernite_1:          HyperrogueLocationData("Irradiated Field",          hyperrogue_base_id + 0x037),
    LocationName.water_lily_1:          HyperrogueLocationData("Wetland",                   hyperrogue_base_id + 0x038),
    LocationName.gold_ball_1:           HyperrogueLocationData("Frog Park",                 hyperrogue_base_id + 0x039),
    LocationName.lazurite_figurine_1:   HyperrogueLocationData("Eclectic City",             hyperrogue_base_id + 0x03A),
    LocationName.capon_stone_1:         HyperrogueLocationData("Cursed Canyon",             hyperrogue_base_id + 0x03B),
    LocationName.crystal_die_1:         HyperrogueLocationData("Dice Reserve",              hyperrogue_base_id + 0x03C),
}

nonstandard_unlock_location_data_table: Dict[str, HyperrogueLocationData] = {
    LocationName.bounty_1:              HyperrogueLocationData("Wild West",                 hyperrogue_base_id + 0x050),
    LocationName.treat_1:               HyperrogueLocationData("Halloween",                 hyperrogue_base_id + 0x051),
    LocationName.glowing_crystal_1:     HyperrogueLocationData("Crystal Caverns",           hyperrogue_base_id + 0x052),
    LocationName.snake_oil_1:           HyperrogueLocationData("Snake Nest",                hyperrogue_base_id + 0x053),
    LocationName.sea_glass_1:           HyperrogueLocationData("Docks",                     hyperrogue_base_id + 0x054),
    LocationName.fuel_1:                HyperrogueLocationData("Space Rocks",               hyperrogue_base_id + 0x055),
}

orb_unlock_location_data_table: Dict[str, HyperrogueLocationData] = {
    LocationName.ice_diamond_2:         HyperrogueLocationData("Icy Land",                  hyperrogue_base_id + 0x100),
    LocationName.gold_2:                HyperrogueLocationData("Living Caves",              hyperrogue_base_id + 0x101),
    LocationName.spice_2:               HyperrogueLocationData("Desert",                    hyperrogue_base_id + 0x102),
    LocationName.ruby_2:                HyperrogueLocationData("Jungle",                    hyperrogue_base_id + 0x103),
    LocationName.elixir_of_life_2:      HyperrogueLocationData("Alchemist Lab",             hyperrogue_base_id + 0x104),
    LocationName.shard_2:               HyperrogueLocationData("Hall of Mirrors",           hyperrogue_base_id + 0x105),
    LocationName.necromancers_totem_2:  HyperrogueLocationData("Graveyard",                 hyperrogue_base_id + 0x106),
    LocationName.demon_daisy_2:         HyperrogueLocationData("Hell",                      hyperrogue_base_id + 0x107),
    LocationName.statue_of_cthulhu_2:   HyperrogueLocationData("R'Lyeh",                    hyperrogue_base_id + 0x108),
    LocationName.phoenix_feather_2:     HyperrogueLocationData("Land of Eternal Motion",    hyperrogue_base_id + 0x109),
    LocationName.ice_sapphire_2:        HyperrogueLocationData("Cocytus",                   hyperrogue_base_id + 0x10A),
    LocationName.fern_flower_2:         HyperrogueLocationData("Dry Forest",                hyperrogue_base_id + 0x10B),
    LocationName.wine_2:                HyperrogueLocationData("Vineyard",                  hyperrogue_base_id + 0x10C),
    LocationName.silver_2:              HyperrogueLocationData("Dead Caves",                hyperrogue_base_id + 0x10D),
    LocationName.royal_jelly_2:         HyperrogueLocationData("Hive",                      hyperrogue_base_id + 0x10E),
    LocationName.emerald_2:             HyperrogueLocationData("Emerald Mines",             hyperrogue_base_id + 0x10F),
    LocationName.powerstone_2:          HyperrogueLocationData("Land of Power",             hyperrogue_base_id + 0x110),
    LocationName.holy_grail_2:          HyperrogueLocationData("Camelot",                   hyperrogue_base_id + 0x111),
    LocationName.grimoire_2:            HyperrogueLocationData("Temple of Cthulhu",         hyperrogue_base_id + 0x112),
    LocationName.pirate_treasure_2:     HyperrogueLocationData("Carribean",                 hyperrogue_base_id + 0x113),
    LocationName.red_gem_2:             HyperrogueLocationData("Red Rock Valley",           hyperrogue_base_id + 0x114),
    LocationName.bomberbird_egg_2:      HyperrogueLocationData("Minefield",                 hyperrogue_base_id + 0x115),
    LocationName.amber_2:               HyperrogueLocationData("Ocean",                     hyperrogue_base_id + 0x116),
    LocationName.pearl_2:               HyperrogueLocationData("Whirlpool",                 hyperrogue_base_id + 0x117),
    LocationName.hypersian_rug_2:       HyperrogueLocationData("Palace",                    hyperrogue_base_id + 0x118),
    LocationName.garnet_2:              HyperrogueLocationData("Living Fjord",              hyperrogue_base_id + 0x119),
    LocationName.ivory_figurine_2:      HyperrogueLocationData("Ivory Tower",               hyperrogue_base_id + 0x11A),
    LocationName.onyx_2:                HyperrogueLocationData("Zebra",                     hyperrogue_base_id + 0x11B),
    LocationName.elemental_gem_2:       HyperrogueLocationData("Elemental Planes",          hyperrogue_base_id + 0x11C),
    LocationName.fulgurite_2:           HyperrogueLocationData("Land of Storms",            hyperrogue_base_id + 0x11D),
    LocationName.mutant_sapling_2:      HyperrogueLocationData("Overgrown Woods",           hyperrogue_base_id + 0x11E),
    LocationName.mutant_fruit_2:        HyperrogueLocationData("Clearing",                  hyperrogue_base_id + 0x11F),
    LocationName.black_lotus_2:         HyperrogueLocationData("Haunted Woods",             hyperrogue_base_id + 0x120),
    LocationName.white_dove_feather_2:  HyperrogueLocationData("Windy Plains",              hyperrogue_base_id + 0x121),
    LocationName.thornless_rose_2:      HyperrogueLocationData("Rose Garden",               hyperrogue_base_id + 0x122),
    LocationName.coral_2:               HyperrogueLocationData("Warped Coast",              hyperrogue_base_id + 0x123),
    LocationName.baby_tortoise_2:       HyperrogueLocationData("Galapagos",                 hyperrogue_base_id + 0x124),
    LocationName.apple_2:               HyperrogueLocationData("Yendorian Forest",          hyperrogue_base_id + 0x125),
    LocationName.dragon_scale_2:        HyperrogueLocationData("Dragon Chasms",             hyperrogue_base_id + 0x126),
    LocationName.sunken_treasure_2:     HyperrogueLocationData("Kraken Depths",             hyperrogue_base_id + 0x127),
    LocationName.ancient_jewelry_2:     HyperrogueLocationData("Burial Grounds",            hyperrogue_base_id + 0x128),
    LocationName.golden_egg_2:          HyperrogueLocationData("Trollheim",                 hyperrogue_base_id + 0x129),
    LocationName.slime_mold_2:          HyperrogueLocationData("Dungeon",                   hyperrogue_base_id + 0x12A),
    LocationName.amethyst_2:            HyperrogueLocationData("Lost Mountain",             hyperrogue_base_id + 0x12B),
    LocationName.dodecahedron_2:        HyperrogueLocationData("Reptiles",                  hyperrogue_base_id + 0x12C),
    LocationName.green_grass_2:         HyperrogueLocationData("Prairie",                   hyperrogue_base_id + 0x12D),
    LocationName.spinel_2:              HyperrogueLocationData("Bull Dash",                 hyperrogue_base_id + 0x12E),
    LocationName.lava_lily_2:           HyperrogueLocationData("Volcanic Wasteland",        hyperrogue_base_id + 0x12F),
    LocationName.turquoise_2:           HyperrogueLocationData("Hunting Ground",            hyperrogue_base_id + 0x130),
    LocationName.forgotten_relic_2:     HyperrogueLocationData("Blizzard",                  hyperrogue_base_id + 0x131),
    LocationName.ancient_weapon_2:      HyperrogueLocationData("Terracotta Army",           hyperrogue_base_id + 0x132),
    LocationName.chrysoberyl_2:         HyperrogueLocationData("Ruined City",               hyperrogue_base_id + 0x133),
    LocationName.tasty_jelly_2:         HyperrogueLocationData("Jelly Kingdom",             hyperrogue_base_id + 0x134),
    LocationName.tigers_eye_2:          HyperrogueLocationData("Brown Island",              hyperrogue_base_id + 0x135),
    LocationName.meteorite_2:           HyperrogueLocationData("Free Fall",                 hyperrogue_base_id + 0x136),
    LocationName.torbernite_2:          HyperrogueLocationData("Irradiated Field",          hyperrogue_base_id + 0x137),
    LocationName.water_lily_2:          HyperrogueLocationData("Wetland",                   hyperrogue_base_id + 0x138),
    LocationName.gold_ball_2:           HyperrogueLocationData("Frog Park",                 hyperrogue_base_id + 0x139),
    LocationName.lazurite_figurine_2:   HyperrogueLocationData("Eclectic City",             hyperrogue_base_id + 0x13A),
    LocationName.capon_stone_2:         HyperrogueLocationData("Cursed Canyon",             hyperrogue_base_id + 0x13B),
    LocationName.crystal_die_2:         HyperrogueLocationData("Dice Reserve",              hyperrogue_base_id + 0x13C),
}

nonstandard_orb_unlock_location_data_table: Dict[str, HyperrogueLocationData] = {
    LocationName.bounty_2:              HyperrogueLocationData("Wild West",                 hyperrogue_base_id + 0x150),
    LocationName.treat_2:               HyperrogueLocationData("Halloween",                 hyperrogue_base_id + 0x151),
    LocationName.glowing_crystal_2:     HyperrogueLocationData("Crystal Caverns",           hyperrogue_base_id + 0x152),
    LocationName.snake_oil_2:           HyperrogueLocationData("Snake Nest",                hyperrogue_base_id + 0x153),
    LocationName.sea_glass_2:           HyperrogueLocationData("Docks",                     hyperrogue_base_id + 0x154),
    LocationName.fuel_2:                HyperrogueLocationData("Space Rocks",               hyperrogue_base_id + 0x155),
}

global_orb_unlock_location_data_table: Dict[str, HyperrogueLocationData] = {
    LocationName.ice_diamond_3:         HyperrogueLocationData("Icy Land",                  hyperrogue_base_id + 0x200),
    LocationName.gold_3:                HyperrogueLocationData("Living Caves",              hyperrogue_base_id + 0x201),
    LocationName.spice_3:               HyperrogueLocationData("Desert",                    hyperrogue_base_id + 0x202),
    LocationName.ruby_3:                HyperrogueLocationData("Jungle",                    hyperrogue_base_id + 0x203),
    LocationName.elixir_of_life_3:      HyperrogueLocationData("Alchemist Lab",             hyperrogue_base_id + 0x204),
    LocationName.shard_3:               HyperrogueLocationData("Hall of Mirrors",           hyperrogue_base_id + 0x205),
    LocationName.necromancers_totem_3:  HyperrogueLocationData("Graveyard",                 hyperrogue_base_id + 0x206),
    LocationName.demon_daisy_3:         HyperrogueLocationData("Hell",                      hyperrogue_base_id + 0x207),
    LocationName.statue_of_cthulhu_3:   HyperrogueLocationData("R'Lyeh",                    hyperrogue_base_id + 0x208),
    LocationName.phoenix_feather_3:     HyperrogueLocationData("Land of Eternal Motion",    hyperrogue_base_id + 0x209),
    LocationName.ice_sapphire_3:        HyperrogueLocationData("Cocytus",                   hyperrogue_base_id + 0x20A),
    LocationName.fern_flower_3:         HyperrogueLocationData("Dry Forest",                hyperrogue_base_id + 0x20B),
    LocationName.wine_3:                HyperrogueLocationData("Vineyard",                  hyperrogue_base_id + 0x20C),
    LocationName.silver_3:              HyperrogueLocationData("Dead Caves",                hyperrogue_base_id + 0x20D),
    LocationName.royal_jelly_3:         HyperrogueLocationData("Hive",                      hyperrogue_base_id + 0x20E),
    LocationName.emerald_3:             HyperrogueLocationData("Emerald Mines",             hyperrogue_base_id + 0x20F),
    LocationName.powerstone_3:          HyperrogueLocationData("Land of Power",             hyperrogue_base_id + 0x210),
    LocationName.holy_grail_3:          HyperrogueLocationData("Camelot",                   hyperrogue_base_id + 0x211),
    LocationName.grimoire_3:            HyperrogueLocationData("Temple of Cthulhu",         hyperrogue_base_id + 0x212),
    LocationName.pirate_treasure_3:     HyperrogueLocationData("Carribean",                 hyperrogue_base_id + 0x213),
    LocationName.red_gem_3:             HyperrogueLocationData("Red Rock Valley",           hyperrogue_base_id + 0x214),
    LocationName.bomberbird_egg_3:      HyperrogueLocationData("Minefield",                 hyperrogue_base_id + 0x215),
    LocationName.amber_3:               HyperrogueLocationData("Ocean",                     hyperrogue_base_id + 0x216),
    LocationName.pearl_3:               HyperrogueLocationData("Whirlpool",                 hyperrogue_base_id + 0x217),
    LocationName.hypersian_rug_3:       HyperrogueLocationData("Palace",                    hyperrogue_base_id + 0x218),
    LocationName.garnet_3:              HyperrogueLocationData("Living Fjord",              hyperrogue_base_id + 0x219),
    LocationName.ivory_figurine_3:      HyperrogueLocationData("Ivory Tower",               hyperrogue_base_id + 0x21A),
    LocationName.onyx_3:                HyperrogueLocationData("Zebra",                     hyperrogue_base_id + 0x21B),
    LocationName.elemental_gem_3:       HyperrogueLocationData("Elemental Planes",          hyperrogue_base_id + 0x21C),
    LocationName.fulgurite_3:           HyperrogueLocationData("Land of Storms",            hyperrogue_base_id + 0x21D),
    LocationName.mutant_sapling_3:      HyperrogueLocationData("Overgrown Woods",           hyperrogue_base_id + 0x21E),
    LocationName.mutant_fruit_3:        HyperrogueLocationData("Clearing",                  hyperrogue_base_id + 0x21F),
    LocationName.black_lotus_3:         HyperrogueLocationData("Haunted Woods",             hyperrogue_base_id + 0x220),
    LocationName.white_dove_feather_3:  HyperrogueLocationData("Windy Plains",              hyperrogue_base_id + 0x221),
    LocationName.thornless_rose_3:      HyperrogueLocationData("Rose Garden",               hyperrogue_base_id + 0x222),
    LocationName.coral_3:               HyperrogueLocationData("Warped Coast",              hyperrogue_base_id + 0x223),
    LocationName.baby_tortoise_3:       HyperrogueLocationData("Galapagos",                 hyperrogue_base_id + 0x224),
    LocationName.apple_3:               HyperrogueLocationData("Yendorian Forest",          hyperrogue_base_id + 0x225),
    LocationName.dragon_scale_3:        HyperrogueLocationData("Dragon Chasms",             hyperrogue_base_id + 0x226),
    LocationName.sunken_treasure_3:     HyperrogueLocationData("Kraken Depths",             hyperrogue_base_id + 0x227),
    LocationName.ancient_jewelry_3:     HyperrogueLocationData("Burial Grounds",            hyperrogue_base_id + 0x228),
    LocationName.golden_egg_3:          HyperrogueLocationData("Trollheim",                 hyperrogue_base_id + 0x229),
    LocationName.slime_mold_3:          HyperrogueLocationData("Dungeon",                   hyperrogue_base_id + 0x22A),
    LocationName.amethyst_3:            HyperrogueLocationData("Lost Mountain",             hyperrogue_base_id + 0x22B),
    LocationName.dodecahedron_3:        HyperrogueLocationData("Reptiles",                  hyperrogue_base_id + 0x22C),
    LocationName.green_grass_3:         HyperrogueLocationData("Prairie",                   hyperrogue_base_id + 0x22D),
    LocationName.spinel_3:              HyperrogueLocationData("Bull Dash",                 hyperrogue_base_id + 0x22E),
    LocationName.lava_lily_3:           HyperrogueLocationData("Volcanic Wasteland",        hyperrogue_base_id + 0x22F),
    LocationName.turquoise_3:           HyperrogueLocationData("Hunting Ground",            hyperrogue_base_id + 0x230),
    LocationName.forgotten_relic_3:     HyperrogueLocationData("Blizzard",                  hyperrogue_base_id + 0x231),
    LocationName.ancient_weapon_3:      HyperrogueLocationData("Terracotta Army",           hyperrogue_base_id + 0x232),
    LocationName.chrysoberyl_3:         HyperrogueLocationData("Ruined City",               hyperrogue_base_id + 0x233),
    LocationName.tasty_jelly_3:         HyperrogueLocationData("Jelly Kingdom",             hyperrogue_base_id + 0x234),
    LocationName.tigers_eye_3:          HyperrogueLocationData("Brown Island",              hyperrogue_base_id + 0x235),
    LocationName.meteorite_3:           HyperrogueLocationData("Free Fall",                 hyperrogue_base_id + 0x236),
    LocationName.torbernite_3:          HyperrogueLocationData("Irradiated Field",          hyperrogue_base_id + 0x237),
    LocationName.water_lily_3:          HyperrogueLocationData("Wetland",                   hyperrogue_base_id + 0x238),
    LocationName.gold_ball_3:           HyperrogueLocationData("Frog Park",                 hyperrogue_base_id + 0x239),
    LocationName.lazurite_figurine_3:   HyperrogueLocationData("Eclectic City",             hyperrogue_base_id + 0x23A),
    LocationName.capon_stone_3:         HyperrogueLocationData("Cursed Canyon",             hyperrogue_base_id + 0x23B),
    LocationName.crystal_die_3:         HyperrogueLocationData("Dice Reserve",              hyperrogue_base_id + 0x23C),
}

nonstandard_global_orb_unlock_location_data_table: Dict[str, HyperrogueLocationData] = {
    LocationName.bounty_3:              HyperrogueLocationData("Wild West",                 hyperrogue_base_id + 0x250),
    LocationName.treat_3:               HyperrogueLocationData("Halloween",                 hyperrogue_base_id + 0x251),
    LocationName.glowing_crystal_3:     HyperrogueLocationData("Crystal Caverns",           hyperrogue_base_id + 0x252),
    LocationName.snake_oil_3:           HyperrogueLocationData("Snake Nest",                hyperrogue_base_id + 0x253),
    LocationName.sea_glass_3:           HyperrogueLocationData("Docks",                     hyperrogue_base_id + 0x254),
    LocationName.fuel_3:                HyperrogueLocationData("Space Rocks",               hyperrogue_base_id + 0x255),
}

completion_location_data_table: Dict[str, HyperrogueLocationData] = {
    LocationName.ice_diamond_4:         HyperrogueLocationData("Icy Land",                  hyperrogue_base_id + 0x300),
    LocationName.gold_4:                HyperrogueLocationData("Living Caves",              hyperrogue_base_id + 0x301),
    LocationName.spice_4:               HyperrogueLocationData("Desert",                    hyperrogue_base_id + 0x302),
    LocationName.ruby_4:                HyperrogueLocationData("Jungle",                    hyperrogue_base_id + 0x303),
    LocationName.elixir_of_life_4:      HyperrogueLocationData("Alchemist Lab",             hyperrogue_base_id + 0x304),
    LocationName.shard_4:               HyperrogueLocationData("Hall of Mirrors",           hyperrogue_base_id + 0x305),
    LocationName.necromancers_totem_4:  HyperrogueLocationData("Graveyard",                 hyperrogue_base_id + 0x306),
    LocationName.demon_daisy_4:         HyperrogueLocationData("Hell",                      hyperrogue_base_id + 0x307),
    LocationName.statue_of_cthulhu_4:   HyperrogueLocationData("R'Lyeh",                    hyperrogue_base_id + 0x308),
    LocationName.phoenix_feather_4:     HyperrogueLocationData("Land of Eternal Motion",    hyperrogue_base_id + 0x309),
    LocationName.ice_sapphire_4:        HyperrogueLocationData("Cocytus",                   hyperrogue_base_id + 0x30A),
    LocationName.fern_flower_4:         HyperrogueLocationData("Dry Forest",                hyperrogue_base_id + 0x30B),
    LocationName.wine_4:                HyperrogueLocationData("Vineyard",                  hyperrogue_base_id + 0x30C),
    LocationName.silver_4:              HyperrogueLocationData("Dead Caves",                hyperrogue_base_id + 0x30D),
    LocationName.royal_jelly_4:         HyperrogueLocationData("Hive",                      hyperrogue_base_id + 0x30E),
    LocationName.emerald_4:             HyperrogueLocationData("Emerald Mines",             hyperrogue_base_id + 0x30F),
    LocationName.powerstone_4:          HyperrogueLocationData("Land of Power",             hyperrogue_base_id + 0x310),
    LocationName.holy_grail_4:          HyperrogueLocationData("Camelot",                   hyperrogue_base_id + 0x311),
    LocationName.grimoire_4:            HyperrogueLocationData("Temple of Cthulhu",         hyperrogue_base_id + 0x312),
    LocationName.pirate_treasure_4:     HyperrogueLocationData("Carribean",                 hyperrogue_base_id + 0x313),
    LocationName.red_gem_4:             HyperrogueLocationData("Red Rock Valley",           hyperrogue_base_id + 0x314),
    LocationName.bomberbird_egg_4:      HyperrogueLocationData("Minefield",                 hyperrogue_base_id + 0x315),
    LocationName.amber_4:               HyperrogueLocationData("Ocean",                     hyperrogue_base_id + 0x316),
    LocationName.pearl_4:               HyperrogueLocationData("Whirlpool",                 hyperrogue_base_id + 0x317),
    LocationName.hypersian_rug_4:       HyperrogueLocationData("Palace",                    hyperrogue_base_id + 0x318),
    LocationName.garnet_4:              HyperrogueLocationData("Living Fjord",              hyperrogue_base_id + 0x319),
    LocationName.ivory_figurine_4:      HyperrogueLocationData("Ivory Tower",               hyperrogue_base_id + 0x31A),
    LocationName.onyx_4:                HyperrogueLocationData("Zebra",                     hyperrogue_base_id + 0x31B),
    LocationName.elemental_gem_4:       HyperrogueLocationData("Elemental Planes",          hyperrogue_base_id + 0x31C),
    LocationName.fulgurite_4:           HyperrogueLocationData("Land of Storms",            hyperrogue_base_id + 0x31D),
    LocationName.mutant_sapling_4:      HyperrogueLocationData("Overgrown Woods",           hyperrogue_base_id + 0x31E),
    LocationName.mutant_fruit_4:        HyperrogueLocationData("Clearing",                  hyperrogue_base_id + 0x31F),
    LocationName.black_lotus_4:         HyperrogueLocationData("Haunted Woods",             hyperrogue_base_id + 0x320),
    LocationName.white_dove_feather_4:  HyperrogueLocationData("Windy Plains",              hyperrogue_base_id + 0x321),
    LocationName.thornless_rose_4:      HyperrogueLocationData("Rose Garden",               hyperrogue_base_id + 0x322),
    LocationName.coral_4:               HyperrogueLocationData("Warped Coast",              hyperrogue_base_id + 0x323),
    LocationName.baby_tortoise_4:       HyperrogueLocationData("Galapagos",                 hyperrogue_base_id + 0x324),
    LocationName.apple_4:               HyperrogueLocationData("Yendorian Forest",          hyperrogue_base_id + 0x325),
    LocationName.dragon_scale_4:        HyperrogueLocationData("Dragon Chasms",             hyperrogue_base_id + 0x326),
    LocationName.sunken_treasure_4:     HyperrogueLocationData("Kraken Depths",             hyperrogue_base_id + 0x327),
    LocationName.ancient_jewelry_4:     HyperrogueLocationData("Burial Grounds",            hyperrogue_base_id + 0x328),
    LocationName.golden_egg_4:          HyperrogueLocationData("Trollheim",                 hyperrogue_base_id + 0x329),
    LocationName.slime_mold_4:          HyperrogueLocationData("Dungeon",                   hyperrogue_base_id + 0x32A),
    LocationName.amethyst_4:            HyperrogueLocationData("Lost Mountain",             hyperrogue_base_id + 0x32B),
    LocationName.dodecahedron_4:        HyperrogueLocationData("Reptiles",                  hyperrogue_base_id + 0x32C),
    LocationName.green_grass_4:         HyperrogueLocationData("Prairie",                   hyperrogue_base_id + 0x32D),
    LocationName.spinel_4:              HyperrogueLocationData("Bull Dash",                 hyperrogue_base_id + 0x32E),
    LocationName.lava_lily_4:           HyperrogueLocationData("Volcanic Wasteland",        hyperrogue_base_id + 0x32F),
    LocationName.turquoise_4:           HyperrogueLocationData("Hunting Ground",            hyperrogue_base_id + 0x330),
    LocationName.forgotten_relic_4:     HyperrogueLocationData("Blizzard",                  hyperrogue_base_id + 0x331),
    LocationName.ancient_weapon_4:      HyperrogueLocationData("Terracotta Army",           hyperrogue_base_id + 0x332),
    LocationName.chrysoberyl_4:         HyperrogueLocationData("Ruined City",               hyperrogue_base_id + 0x333),
    LocationName.tasty_jelly_4:         HyperrogueLocationData("Jelly Kingdom",             hyperrogue_base_id + 0x334),
    LocationName.tigers_eye_4:          HyperrogueLocationData("Brown Island",              hyperrogue_base_id + 0x335),
    LocationName.meteorite_4:           HyperrogueLocationData("Free Fall",                 hyperrogue_base_id + 0x336),
    LocationName.torbernite_4:          HyperrogueLocationData("Irradiated Field",          hyperrogue_base_id + 0x337),
    LocationName.water_lily_4:          HyperrogueLocationData("Wetland",                   hyperrogue_base_id + 0x338),
    LocationName.gold_ball_4:           HyperrogueLocationData("Frog Park",                 hyperrogue_base_id + 0x339),
    LocationName.lazurite_figurine_4:   HyperrogueLocationData("Eclectic City",             hyperrogue_base_id + 0x33A),
    LocationName.capon_stone_4:         HyperrogueLocationData("Cursed Canyon",             hyperrogue_base_id + 0x33B),
    LocationName.crystal_die_4:         HyperrogueLocationData("Dice Reserve",              hyperrogue_base_id + 0x33C),
}

nonstandard_completion_location_data_table: Dict[str, HyperrogueLocationData] = {
    LocationName.bounty_4:              HyperrogueLocationData("Wild West",                 hyperrogue_base_id + 0x350),
    LocationName.treat_4:               HyperrogueLocationData("Halloween",                 hyperrogue_base_id + 0x351),
    LocationName.glowing_crystal_4:     HyperrogueLocationData("Crystal Caverns",           hyperrogue_base_id + 0x352),
    LocationName.snake_oil_4:           HyperrogueLocationData("Snake Nest",                hyperrogue_base_id + 0x353),
    LocationName.sea_glass_4:           HyperrogueLocationData("Docks",                     hyperrogue_base_id + 0x354),
    LocationName.fuel_4:                HyperrogueLocationData("Space Rocks",               hyperrogue_base_id + 0x355),
}

standard_location_data_table: Dict[str, HyperrogueLocationData] = {**unlock_location_data_table,
                                                         **orb_unlock_location_data_table,
                                                         **global_orb_unlock_location_data_table,
                                                         **completion_location_data_table}

nonstandard_location_data_table: Dict[str, HyperrogueLocationData] = {**nonstandard_unlock_location_data_table,
                                                         **nonstandard_orb_unlock_location_data_table,
                                                         **nonstandard_global_orb_unlock_location_data_table,
                                                         **nonstandard_completion_location_data_table}

location_data_table: Dict[str, HyperrogueLocationData] = {**standard_location_data_table,
                                                          **nonstandard_location_data_table}

location_table = {name: data.address for name, data in location_data_table.items() if data.address is not None}
