from typing import Dict, List

landtable: Dict[str, int] = {
    "Icy Land":                 0x00,
    "Living Cave":              0x01,
    "Desert":                   0x02,
    "Jungle":                   0x03,
    "Alchemist Lab":            0x04,
    "Hall of Mirrors":          0x05,
    "Graveyard":                0x06,
    "Hell":                     0x07,
    "R'Lyeh":                   0x08,
    "Land of Eternal Motion":   0x09,
    "Cocytus":                  0x0A,
    "Dry Forest":               0x0B,
    "Vineyard":                 0x0C,
    "Dead Cave":                0x0D,
    "Hive":                     0x0E,
    "Emerald Mine":             0x0F,
    "Land of Power":            0x10,
    # Camelot is a special land, hence at the bottom
    "Temple of Cthulhu":        0x12,
    "Carribean":                0x13,
    "Red Rock Valley":          0x14,
    "Minefield":                0x15,
    "Ocean":                    0x16,
    "Whirlpool":                0x17,
    "Palace":                   0x18,
    "Living Fjord":             0x19,
    "Ivory Tower":              0x1A,
    "Zebra":                    0x1B,
    "Elemental Planes":         0x1C,
    "Land of Storms":           0x1D,
    "Overgrown Woods":          0x1E,
    "Clearing":                 0x1F,
    "Haunted Woods":            0x20,
    "Windy Plains":             0x21,
    "Rose Garden":              0x22,
    "Warped Coast":             0x23,
    "Galapagos":                0x24,
    "Yendorian Forest":         0x25,
    "Dragon Chasms":            0x26,
    "Kraken Depths":            0x27,
    "Burial Grounds":           0x28,
    "Trollheim":                0x29,
    "Dungeon":                  0x2A,
    "Lost Mountain":            0x2B,
    "Reptiles":                 0x2C,
    "Prairie":                  0x2D,
    "Bull Dash":                0x2E,
    "Volcanic Wasteland":       0x2F,
    "Hunting Ground":           0x30,
    "Blizzard":                 0x31,
    "Terracotta Army":          0x32,
    "Ruined City":              0x33,
    "Jelly Kingdom":            0x34,
    "Brown Island":             0x35,
    "Free Fall":                0x36,
    "Irradiated Field":         0x37,
    "Wetland":                  0x38,
    "Frog Park":                0x39,
    "Eclectic City":            0x3A,
    "Cursed Canyon":            0x3B,
    "Dice Reserve":             0x3C,
    # Special lands
    "Camelot":                  0x11,
}

landlist: List[str] = landtable.keys()

orbtable: Dict[str, int] = {
    "Orb of Flash":                 0x00,
    "Orb of Life":                  0x01,
    "Orb of Shielding":             0x02,
    "Orb of Storms":                0x03,
    "Orb of Speed":                 0x04,
    "Orb of the Mirror":            0x05,
    "Dead Orb":                     0x06,
 #   "Orb of Yendor":               0x07,
    "Orb of Teleport":              0x08,
    "Orb of Safety":                0x09,
    "Orb of Change":                0x0A,
    "Orb of Thorns":                0x0B,
    "Orb of Aether":                0x0C,
    "Orb of Earth":                 0x0D,
    "Orb of Invisibility":          0x0E,
    "Orb of the Mind":              0x0F,
    "Orb of Fire":                  0x10,
    # Camelot is a special land, hence at the bottom
    "Orb of the Dragon":            0x12,
    "Orb of Time":                  0x13,
    "Orb of Space":                 0x14,
    "Orb of Friendship":            0x15,
    "Orb of Empathy":               0x16,
    "Orb of Water":                 0x17,
    "Orb of Discord":               0x18,
    "Orb of the Fish":              0x19,
    "Orb of Matter":                0x1A,
    "Orb of the Frog":              0x1B,
    "Orb of Summoning":             0x1C,
    "Orb of Stunning":              0x1D,
    "Orb of the Woods":             0x1E,
    "Orb of Freedom":               0x1F,
    "Orb of Undeath":               0x20,
    "Orb of Air":                   0x21,
    "Orb of Beauty":                0x22,
    "Orb of the Warp":              0x23,
    "Orb of the Shell":             0x24,
    "Orb of Energy":                0x25,
    "Orb of Domination":            0x26,
    "Orb of the Sword":             0x27,
    "Orb of the Sword II":          0x28,
    "Orb of the Stone":             0x29,
    "Orb of Recall":                0x2A,
    "Orb of Nature":                0x2B,
    "Orb of Vaulting":              0x2C,
    "Orb of the Bull":              0x2D,
    "Orb of Horns":                 0x2E,
    "Orb of Lava":                  0x2F,
    "Orb of Ferocity":              0x30,
    "Orb of Winter":                0x31,
    "Orb of Slashing":              0x32,
    "Orb of Slaying":               0x33,
    "Orb of Phasing":               0x34,
    "Orb of Choice":                0x35,
    "Orb of Gravity":               0x36,
    "Orb of Intensity":             0x37,
    "Orb of Plague":                0x38,
    "Orb of Impact":                0x39,
    "Orb of Chaos":                 0x3A,
    "Orb of Purity":                0x3B,
    "Orb of Luck":                  0x3C,
    "Orb of Trickery":              0x11,
}

orblist : List[str] = orbtable.keys()